### ISSUE TITLE
Using the package from npm install fails

### ISSUE THREAD

**Issue by richardschneider** [WHenderson/json-pointer-rfc6901#2]
Getting the error `Error: Cannot find module './dist/json-pointer.node.js'` when I `require` the package.

I did a simple `npm install json-pointer-rfc6091` and then tried to use the package.

Looks like you forgot to include the `dist` folder in the npm package.

**Comment by WHenderson** [comment]
Fixed my package.json and release procedure. 
npm install now includes the missing folder. 

Let me know how you get on

**Comment by richardschneider** [comment]
Thanks it working just fine now.
